return {
	VERSION = "0.0.1",
	AUTHOR = "ZenithyHeavens",
	
	NAME = "CodeBlocks CORE",
	DESCRIPTION = "The core module for CodeBlocks, removed it, nothing work!",
	TAGS = {"CORE"},

	VERIFICATION_DATE = "2025-11-04",
	VERIFICATION_KEY = [[]], --If incorrect, it will fall back to "Community" source.
	CORE_KEY = [[]], --Anti-Softlock System, most Mods will not have to add it since your Mod will not load properly without the correct one.
	
	MODID = "core",
	mc = require(script.Parent)
}